package net.uncorp.ipeekr.data

import android.content.Context
import java.util.zip.GZIPInputStream

/**
 * MAC address -> vendor, from assets/oui.tsv.gz (generated by scripts/gen-oui.py from Wireshark's manuf).
 * The file is streamed on each lookup (~60k lines, a few ms); callers cache the result per BSSID.
 */
object Oui {
    fun vendor(ctx: Context, mac: String?): String? {
        val hex = mac?.filter { it.isLetterOrDigit() }?.uppercase()?.takeIf { it.length == 12 } ?: return null
        if (Format.isRandomMac(mac)) return "Private (random MAC)"
        val keys = setOf(hex.take(9), hex.take(7), hex.take(6))
        var best: Pair<String, String>? = null
        runCatching {
            GZIPInputStream(ctx.assets.open("oui.tsv.gz")).bufferedReader().useLines { lines ->
                for (line in lines) {
                    val tab = line.indexOf('\t')
                    if (tab <= 0) continue
                    val k = line.substring(0, tab)
                    if (k in keys && (best == null || k.length > best!!.first.length)) best = k to line.substring(tab + 1)
                }
            }
        }
        return best?.second
    }
}
