#!/usr/bin/env python3
"""Regenerate the launcher icon drawables from art/ipeekr.svg (512px pixel art made of <rect>s).

usage: scripts/gen-icon.py
"""
import os
import re

root = os.path.join(os.path.dirname(__file__), "..")
svg = open(os.path.join(root, "art/ipeekr.svg")).read()
rects = re.findall(r'<rect x="(\d+)" y="(\d+)" width="(\d+)" height="(\d+)" fill="([^"]+)"/>', svg)

by_color = {}
for x, y, w, h, c in rects:
    by_color.setdefault(c.lower(), []).append(f"M{x},{y}h{w}v{h}h-{w}z")

# 512px art -> EYE_DP inside the 108dp adaptive canvas (the safe circle is 66dp; smaller = more margin)
EYE_DP = 52
S = EYE_DP / 512
T = (108 - EYE_DP) / 2


def doc(paths, comment):
    out = [
        '<?xml version="1.0" encoding="utf-8"?>',
        f"<!-- {comment} -->",
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        '    android:width="108dp"',
        '    android:height="108dp"',
        '    android:viewportWidth="108"',
        '    android:viewportHeight="108">',
        f'    <group android:translateX="{T}" android:translateY="{T}" android:scaleX="{S:.6f}" android:scaleY="{S:.6f}">',
    ]
    out += [f'        <path android:fillColor="{color}" android:pathData="{d}" />' for color, d in paths]
    out += ["    </group>", "</vector>", ""]
    return "\n".join(out)


res = os.path.join(root, "app/src/main/res/drawable")
fg = [("@color/ipeekr_black", "".join(by_color["black"])), ("@color/ipeekr_blue", "".join(by_color["#0000ee"]))]
open(os.path.join(res, "ic_launcher_foreground.xml"), "w").write(
    doc(fg, "Generated from art/ipeekr.svg by scripts/gen-icon.py. Do not edit by hand."))
mono = [("#FFFFFFFF", "".join(by_color["black"]) + "".join(by_color["#0000ee"]))]
open(os.path.join(res, "ic_launcher_monochrome.xml"), "w").write(
    doc(mono, "Themed-icon version of art/ipeekr.svg (all ink in one colour). Generated by scripts/gen-icon.py."))
print({k: len(v) for k, v in by_color.items()})
